apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yzna6rgcn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yzna6rgcn-go 
  name: yzna6rgcn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yzna6rgcn-go 
